---
# Setup apache

- name: Create directory
  file:
    path: "{{ item }}"
    state: directory
    mode: "0755"
    owner: root
    group: root
  loop:
    - "{{ download_dir }}"
    - "{{ style_dir }}"

- name: Link from wwwroot
  file:
    src:  "{{ download_dir }}"
    dest: "{{ download_wwwroot }}"
    state: link

- name: Copy style static files
  copy:
    src: "download-style/"
    dest: "{{ style_dir }}/"
    group: apache


- name: Copy download UI template files
  template:
    src: "{{ item }}.j2"
    dest: "{{ style_dir }}/{{ item }}"
    mode: "0755"
  loop:
    - download_error403.html
    - header.html
    - html_header.inc

- name: Generate and copy download_autoindex.conf
  template:
    src: "{{ item }}.conf.j2"
    dest: /etc/httpd/conf.d/{{ item }}.conf
  loop:
    - download_autoindex
  notify: restart httpd
  tags: download_autoindex
