---
# Setup apache

- name: Copy style static files
  copy:
    src: download-style
    dest: "{{ style_dir }}"

- name: Create directory
  file:
    path: "{{ item }}"
    state: directory
    mode: "0755"
    owner: root
    group: root
  loop:
    - "{{ style_dir }}"

- name: Copy download UI template files
  template:
    src: "{{ item }}.j2"
    dest: "{{ style_dir }}/{{ item }}"
  loop:
    - download_error403.html
    - header.html
    - html_header.inc

- name: Generate and copy download_autoindex.conf
  template:
    src: "{{ item }}.conf.j2"
    dest: /etc/httpd/conf.d/{{ item }}.conf
  loop:
    - download_autoindex
