---

- name: Create Pouta VM
  ansible.builtin.import_playbook: pouta-vm.yml

- name: Install Korp software
  ansible.builtin.import_playbook: korp-software-vm.yml

- name: Postprocessing unique to Pouta
  ansible.builtin.import_playbook: pouta-postprocess.yml
