---

- name: Set up Korp and its requirements
  hosts: korp
  become: true

  roles:
      - role: configure-deployment
        tags: configure-deployment
      - role: kielipankki.common.opsview
        tags: opsview
      - role: kielipankki.common.mail_forward
        tags: mail_forward
      - role: apache
        tags: apache
      - role: korp-frontend
        tags: korp-frontend
      - role: korp-backend
        tags: korp-backend
      - role: download
        tags: download
      - role: firewall
        tags: firewall
      - role: geerlingguy.memcached
        tags: memcached
