---

- name: Set up Korp and its requirements
  hosts: korp
  become: true

  roles:
      - role: apache
        tags: apache
      - role: korp-frontend
        tags: korp-frontend
      - role: korp-backend
        tags: korp-backend
      - role: geerlingguy.memcached
        tags: memcached
