---

- name: Create virtual machine on cPouta
  hosts: localhost
  remote_user: almalinux
  become: false
  roles:
    - role: kielipankki.common.create_instances
      tags: create_instances
  vars:
    instance_name: 'korp'
    vm_name_postfix: 'dev'
    pouta_instance_name: "{{ instance_name }}-{{ vm_name_postfix }}"
    std_image: "AlmaLinux-9"
    project_key: "kielipouta"
    project_sg: "portal-sg"
    project_security_groups: "default,{{ project_sg }}" # don't add spaces here!

    servers:
      - name: "{{ pouta_instance_name }}"
        image: "{{ std_image }}"
        flavor: standard.medium
        key_name: "{{ project_key }}"
        security_groups: "{{ project_security_groups }}"
        meta:
          group: default

    security_group_rules:
      - name: ping
        protocol: icmp
        port: -1
        allowed_ips:
          - "193.167.254.68/32" #opsview

      - name: http
        protocol: tcp
        port: 80
        allowed_ips:
          - "192.168.1.0/24" # pouta local network

    authorized_users:
      - ktegel
      - ajarven
      - matthies
      - shardwic
