---

- name: Production-only provisioning steps for Korp
  hosts: korp
  become: true

  tasks:
    - name: Disable SELinux
      selinux:
        policy: targeted
        state: disabled
      register: sestatus

    - name: Read /etc/fstab
      ansible.builtin.slurp:
        src: /etc/fstab
      register: fstab_content

    - name: Warn if swap device appears active
      ansible.builtin.fail:
        msg: "Warning: /etc/fstab appears to have active swap device"
      when: fstab_content['content'] | b64decode is search("^[^#]+swap", multiline=true)

    - name: Restart server if needed
      reboot:
      when: sestatus.changed|default(false)
