---

- name: Production-only provisioning steps for Korp
  hosts: korp
  become: true

  roles:
      - role: fetch_backup
        tags: fetch_backup
      - role: install_csc_commvault_backup
        tags: install_csc_commvault_backup
