---

- name: Production-only provisioning steps for Korp
  hosts: korp
  become: true

  tasks:
    - name: Disable SELinux
      selinux:
        policy: targeted
        state: disabled
      register: sestatus

    - name: Disable swap devices
      ansible.builtin.replace:
        path: /etc/fstab
        regexp: '^([^#\n]+\bswap\b[^\n]+)'
        replace: '# Commented out by Ansible\n# \1'
      register: swap_in_fstab

    - name: Warn if swap device appears active
      ansible.builtin.fail:
        msg: "Warning: /etc/fstab appeared to have active swap device, device disabled, please check"
      when: swap_in_fstab.changed

    - name: Restart server if needed
      reboot:
      when: sestatus.changed|default(false)

