---
# install shibboleth


- name: CentOS/RedHat 7 download shibboleth.repo
  copy: 
    src: shibboleth.repo
    dest: /etc/yum.repos.d/shibboleth.repo

- name: Install Apache shibboleth module
  yum: 
    pkg:
    - httpd
    - shibboleth.x86_64
    - shibboleth-embedded-ds
    - perl-CGI # for shib_test.pl
    state: present
  notify: restart httpd

- name: Move shibboleth conf.d files
  copy: 
    src: "{{ role_path }}/files/httpd/shibboleth/"
    dest: /etc/httpd/conf.d/
  notify: restart httpd
  tags: dl_update

- name: Move shibboleth configuration files
  copy: 
    src: "{{ role_path }}/files/shibboleth/"
    dest: /etc/shibboleth/
  notify: restart shibd
    
- name: Copy certificates
  copy:
    content: "{{ lookup('passwordstore', '{{ item }} returnall=true')}}"
    dest: "/etc/shibboleth/{{ item | basename }}"
  loop: "{{ shib_cert_contents }}"
  notify: restart shibd
  
  
- name: Move shibboleth-ds configuration files
  copy: 
    src: "{{ role_path }}/files/shibboleth-ds/"
    dest: /etc/shibboleth-ds/

- name: Disable SELinux, shibboleth doesnt work otherwise
  selinux:
      state: disabled

- name: shibd service state
  service: 
    name: shibd 
    state: started 
    enabled: yes

