---

- name: Install MariaDB and required packages
  ansible.builtin.yum:
    name:
      - mariadb
      - mariadb-server
      - python3-PyMySQL
    state: present
  become: true

- name: Install MariaDB configuration
  ansible.builtin.copy:
    src: "korp_charset.cnf"
    dest: "/etc/my.cnf.d/"
  become: true

- name: Start MariaDB service
  ansible.builtin.systemd_service:
    name: mariadb
    state: started
    enabled: true
  become: true

- name: Set root password for MariaDB
  community.mysql.mysql_user:
    login_user: root
    name: root
    password: "{{ db_root_password }}"
    check_implicit_admin: true
    login_unix_socket: /var/lib/mysql/mysql.sock
  become: true
  ignore_errors: true  # This is only possible when doing the initial install

- name: Send table creation sql files to Korp
  ansible.builtin.copy:
    src: "{{ item }}-tables.sql"
    dest: "/tmp/{{ item }}-tables.sql"
  loop:
    - korp
    - korp_auth

- name: Create databases
  community.mysql.mysql_db:
    login_user: root
    login_password: "{{ db_root_password }}"
    name: "{{ item }}"
    state: import
    target: "/tmp/{{ item }}-tables.sql"
  loop:
    - korp
    - korp_auth

- name: Remove table creation sql files from Korp
  ansible.builtin.file:
    path: "/tmp/{{ item }}-tables.sql"
    state: absent
  loop:
    - korp
    - korp_auth

- name: Create korp user for MariaDB
  community.mysql.mysql_user:
    login_user: root
    login_password: "{{ db_root_password }}"
    user: korp
    password: "{{ korp_db_password }}"
    priv: "korp.*:ALL/korp_auth.*:ALL"
