    - name: Create security group
      os_security_group: name={{ project_sg }}

    - name: Add rule to security group to allow http acess from the internet
      os_security_group_rule:
        security_group: "{{ project_sg }}"
        protocol: tcp
        port_range_min: 80
        port_range_max: 80
        remote_ip_prefix: 0.0.0.0/0

    - name: Add rule to security group to allow https access from the internet
      os_security_group_rule:
        security_group: "{{ project_sg }}"
        protocol: tcp
        port_range_min: 443
        port_range_max: 443
        remote_ip_prefix: 0.0.0.0/0

    - name: Add rule to security group to all ssh from current system
      os_security_group_rule:
        security_group: "{{ project_sg }}"
        protocol: tcp
        port_range_min: 22
        port_range_max: 22
        # roughly CSC, U Helsinki, Taito
        remote_ip_prefix: "{{ item }}"
      with_items:
        - "193.166.0.0/16"
        - "128.214.0.0/16"
        - "86.50.166.0/24"
