---

# handlers file for shibboleth_sp
- name: restart shibd
  service:
    name: shibd
    state: restarted
    enabled: yes
  async: 300
  poll: 0

- name: restart httpd
  service:
    name: httpd
    state: restarted
    enabled: yes
  async: 60
  poll: 0
