---

- name: Create Backup User
  user:
   name: backup
   shell: /bin/bash
   groups: nobody

- name: Install s5cmd for backups
  pip:
    name: s5cmd
    virtualenv: "{{ backup_venv }}"
    virtualenv_python: python3.8  # Temporary workaround for outdated korp2, remove for korp3
  become: true
  become_user: backup

- name: Create backup directories
  file:
   path: "{{ item }}"
   state: directory
   owner: backup
   group: backup
   mode: 0770
  loop:
    - "{{ backup_dir }}"
    - "{{ backup_dir }}/signbank"

- name: Ensure .ssh
  file:
   path: ~/.ssh/
   state: directory
  become: true
  become_user: backup

- name: setup daily backups
  template:
   src: "{{ item }}.j2"
   dest: "/etc/cron.daily/{{ item }}"
   owner: root
   group: backup
   mode: 0750
  loop:
   - get_pouta_webserver_vm_backup
   - sync_korp_servers

- name: Set up weekly backups
  template:
   src: "{{ item }}.j2"
   dest: "/etc/cron.weekly/{{ item }}"
   owner: root
   group: backup
   mode: 0750
  loop:
   - get_signbank_backup

- name: Setup SSH keys
  copy:
   content: "{{ lookup('passwordstore', '{{ item.content }} returnall=true') }}"
   dest: "~/.ssh/{{ item.name }}"
   owner: backup
   group: backup
   mode: 0600
  become: true
  become_user: backup
  loop:
   - {name: id_rsa.pub, content: "{{ backup_id_pub }}"}
   - {name: id_rsa, content: "{{ backup_id_key }}"}

- name: Configure anacron
  ansible.builtin.lineinfile:
   path: /etc/anacrontab
   regexp: '^START_HOURS_RANGE='
   line: "START_HOURS_RANGE={{ anacron_hours }}"
