---

- name: Check if we're doing a Språkbanken build & set related facts
  ansible.builtin.set_fact:
    spraakbanken_build: korp_frontend_repo is search("spraakbanken")
    korp_backend_socket_user: "{{ 'gunicorn' if korp_frontend_repo is search('spraakbanken') else 'apache' }}"
  tags:
    - always
