- name: Set up Språkbanken config dir
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: 0755
    owner: gunicorn
  loop:
    - "{{ korp_frontend_config_home }}"
    - "{{ korp_frontend_config_home }}/app"
    - "{{ korp_frontend_config_home }}/app/translations"
    - "{{ korp_frontend_config_home }}/app/modes"

- name: Install Språkbanken config.yml and translations
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ korp_frontend_config_home }}/app/{{ item.dest }}"
    mode: "0644"
    owner: gunicorn
  loop:
    - src: config.yml.j2
      dest: "config.yml"

- name: Install Språkbanken mode & translation files
  ansible.builtin.copy:
    mode: "0644"
    owner: gunicorn
    src: "{{ item.src }}"
    dest: "{{ korp_frontend_config_home }}/app/{{ item.dest }}"
  loop:
    - src: corpora-eng.json
      dest: /translations/corpora-eng.json
    - src: corpora-swe.json
      dest: /translations/corpora-swe.json
    - src: default_mode.js
      dest: /modes/default_mode.js
