---
# Set firewall in CSC compatible way

- name: Include Pouta iptables configuration
  when: not is_vmware
  include_tasks:
    file: pouta.yml

- name: Include VMWare iptables configuration
  when: is_vmware
  include_tasks:
    file: vmware.yml
