---

- name: Install nftables
  ansible.builtin.dnf:
    name:
      - nftables

- name: Install nftables config (RHEL-based)
  ansible.builtin.copy:
    src: nftables.conf
    dest: /etc/sysconfig/nftables.conf
    owner: root
    group: root
    mode: "0640"
  notify: restart nftables
