---

korp_backend_name: Kielipankki-korp-backend
korp_backend_repo: https://github.com/CSCfi/{{ korp_backend_name }}.git
korp_backend_version: master
korp_backend_auth_version: "authserver/{{ korp_backend_version }}"
korp_backend_plugin_version: "plugins/{{ korp_backend_version }}"
korp_backend_socket: "/run/{{ korp_backend_name }}.sock"
kp_util_scripts_name: Kielipankki-utilities
kp_util_scripts_repo: "https://github.com/CSCfi/{{ kp_util_scripts_name }}"
cwb_svn_repo: https://svn.code.sf.net/p/cwb/code/cwb/trunk
cwb_revision: "r1732"
cwb_registry: /v/corpora/registry
cwb_compile_root: /v/appl/cwb
korp_git_root: /v/appl/korp
korp_backend_home: "{{ korp_git_root }}/{{ korp_backend_name }}"
korp_backend_auth_home: "{{ korp_git_root }}/Kielipankki-korp-backend-auth"
korp_backend_plugin_home: "{{ korp_git_root }}/Kielipankki-korp-backend-plugins"
kp_util_scripts_home: "/v/appl/utils/{{ kp_util_scripts_name }}"
package_cache_dir: "/data1/package_cache"

korp_backend_venv: "{{ korp_git_root }}/{{ korp_backend_name }}/venv"
timezone: "Europe/Helsinki"

korp_db_name: "korp"
korp_db_server: "kielipankkidb9.csc.fi"
korp_db_port: 3306
korp_db_user: "korp"
korp_db_password: "{{ lookup('passwordstore', 'lb_passwords/korp/korp_db_user_password') }}"
backend_cache_dir: "/data1/korp/cache"

mk_base_directories:
  - {path: /data1/, owner: root, group: root, mode: "u+rwx,g+rxs,o+rx"}
  - {path: /data2/, owner: root, group: root, mode: "u+rwx,g+rx,o+rx"}
  - {path: /v/, owner: root, group: root, mode: "u+rwx,g+rwxs,o+rx"}
  - {path: /data1/cwbdata/corpora, owner: root, group: clarin, mode: "u+rwx,g+rwxs,o+rx"}
  - {path: /data1/korp/, owner: root, group: root, mode: "u+rwx,g+rwxs,o+rx"}

v_to_data1_symlinks:
  - {src: /data1/korp, dest: /v/korp}
  - {src: /data1/cwbdata/corpora, dest: /v/corpora}

mk_additional_directories:
  - {path: /data1/cwbdata/korp, owner: root, group: clarin, mode: "u+rwx,g+rwxs,o+rx"}
  - {path: /v/appl/, owner: root, group: root, mode: "u+rwx,g+rwxs,o+rx"}
  - {path: /v/corpora/data, owner: root, group: clarin, mode: "u+rwx,g+rwxs,o+rx"}
  - {path: "{{ cwb_registry }}", owner: root, group: clarin, mode: "u+rwx,g+rwxs,o+rx"}
  - {path: /var/log/korp/, owner: root, group: root, mode: "u+rwx,g+rwxs,o+rx"}
  - {path: /data1/korp/log/, owner: root, group: root, mode: "u+rwx,g+rwxs,o+rwx"} # just because of old cgi stuff
  - {path: "{{ backend_cache_dir }}", owner: gunicorn, group: apache, mode: "u+rwx,g+rwxs,o-rwx"}
  - {path: "{{ korp_git_root }}", owner: root, group: clarin, mode: "u+rwx,g+rwxs,o+rx"}
  - {path: /v/appl/utils/, owner: root, group: clarin, mode: "u+rwx,g+rwxs,o-rwx"}
  - {path: "{{ korp_backend_cgibin_dir }}", owner: root, group: apache, mode: "u+rwx,g+rx,o-rx"}  # for old backend korp.cgi
  - {path: "{{ package_cache_dir }}", owner: root, group: clarin, mode: "u+rwx,g+rwx,o+rx"}

# Should contain list of file names, eg. Sananparsikokoelma_korp_20160725.tgz
korp_pub_packages: []
korp_non_pub_packages: []
